name: octo-ci

on:
  pull_request:
    types: [opened, synchronize]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  generatePlanDeployment:
    name: Teste
    runs-on: ubuntu-latest

    steps:
      - name: Qualquer coisa
        run: echo "Olá"